### ISSUE TITLE
Refactor: Redundant interface encapsulation?

### ISSUE THREAD

**Issue by cheyilin** [wei-z9288/Golang-Practice#5]
All 3 hash types come from std package `crypto` have the same interface `hash.Hash` for checksum calculation.

Could you please try to make the implementation simpler, based on the above fact? Thanks.

https://github.com/wei-z9288/Golang-Practice/blob/d8168dcf1a2115ac7aa1c820d645c930d873e9d8/algo/algo.go#L11-L64

**Comment by weiz-98** [comment]
@CheyiLin I removed the interface and replaced it with GetChecksum() to identify the flags and perform the corresponding actions
